PLATFORM_PATH := device/gameconsole/r36s
TARGET_SCREEN_DENSITY 		:= 195
# Camera
USE_CAMERA_STUB := false

TARGET_KERNEL_CONFIG := lineageos_r36s_defconfig

TARGET_RECOVERY_DEFAULT_ROTATION := ROTATION_LEFT